---
- name: copy metricbeat package if debian/Ubuntu
  copy:
    src: beats_nix/metricbeat-7.9.2-amd64.deb
    dest: /tmp/metricbeat-7.9.2-amd64.deb
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install metricbeat if debian/Ubuntu
  apt:
    deb: /tmp/metricbeat-7.9.2-amd64.deb
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


- name: copy metricbeat package on CentOS/Redhat
  copy:
    src: beats_nix/metricbeat-7.9.2-x86_64.rpm
    dest: /tmp/metricbeat-7.9.2-x86_64.rpm
  when:  ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: install metricbeat if CentOS/Redhat
  yum:
    name: /tmp/metricbeat-7.9.2-x86_64.rpm
  when:  ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


- name: Copy template metricbeat and restart service
  template:
    dest: /etc/metricbeat/metricbeat.yml
    src: beats_nix_templates/metricbeat.yml.j2
  become: yes
  notify: start - metricbeat