- name: Add an Apt signing key for elastic 
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Adding elastic apt repository
  apt_repository: 
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    state: present 
    filename: elastic 
    update_cache: yes


- name: install logstash
  apt: 
    name: elasticsearch
    state: present
    update_cache: yes
