- name: Restart - logstash
  service:
     name: logstash
     state: restarted
     enabled: yes

- name: Stop - logstash
  service:
    name: logstash
    state: stopped
    enabled: yes

- name: Start - logstash
  service:
    name: logstash
    state: started
    enabled: yes