---


- name: Set IP address, Port, Node name, Master node
  lineinfile:
    dest: "{{es_config_dir}}/elasticsearch.yml"
    line: "{{ item.line }}"
  with_items:
    - { line: 'xpack.security.enabled: true' }
    - { line: 'discovery.type: single-node' }
  notify: Restart - ElasticSearch
  become: yes

- name: Setting up bootstrap Password
  command: echo "{{ BOOTSTRAP_PASSWORD }}" | {{ es_home }}/bin/elasticsearch-keystore add "bootstrap.password" -x
  notify: Restart - ElasticSearch
  become: yes

# - name: Wait for port 9200 to become open on the host, don't start checking for 10 seconds
#   wait_for:
#     port: 9200
#     delay: 5
#   delegate_to: "{{ Elasticsearch_IP }}"

- name: Making a super user "Alert"
  command: "{{ es_home }}/bin/elasticsearch-users useradd {{ ProjectUser }} -p {{ ProjectPassword }} -r superuser"
  become: yes
  ignore_errors: yes

- name: Start - ElasticSearch
  service:
    name: elasticsearch
    state: started
    enabled: yes
  become: yes

- name: Resetting elastic password
  uri:
    url:  'http://{{ Elasticsearch_IP }}:{{ Elasticsearch_PORT }}/_security/user/{{ item }}/_password?pretty'
    method: PUT
    user: "{{ ProjectUser }}"
    password: "{{ ProjectPassword }}"
    validate_certs: no
    body_format: json
    body: "{ \"password\" : \"{{ STANDARD_PASSWORD }}\" }"
    headers:
      Content-Type: "application/json"
    #force_basic_auth: yes
  with_items:
    - 'elastic'
    - 'kibana' 
    - 'kibana_system'
    - 'apm_system'
    - 'logstash_system'
    - 'remote_monitoring_user'
    - 'beats_system'
  become: yes
