---

- name: Check that the elastic-certificates.p12 exists
  stat:
    path: /usr/share/elasticsearch/elastic-certificates.p12
  register: stat_result

- name: create certificate for elastic 
  become: yes
  command:  '{{ es_home }}/bin/elasticsearch-certutil cert -out ./elastic-certificates.p12 -pass "" '
  when: not stat_result.stat.exists
 

- name: Copy cert to the proper location
  copy:
    src: '{{ es_home }}/elastic-certificates.p12'
    dest: '{{ es_config_dir }}/elastic-certificates.p12'
    remote_src: yes
    mode: '0644'
  become: yes


- name: Set SSL config for elasticsearch 
  lineinfile:
    dest: "{{ es_config_dir }}/elasticsearch.yml"
    line: "{{ item.line }}"
  with_items:
    - { line: 'xpack.security.enabled: true' }
    - { line: 'xpack.security.transport.ssl.enabled: true' }
    - { line: 'xpack.security.transport.ssl.verification_mode: certificate' }
    - { line: 'xpack.security.transport.ssl.keystore.path: elastic-certificates.p12' }
    - { line: 'xpack.security.transport.ssl.truststore.path: elastic-certificates.p12' }
  become: yes
  notify: Restart - ElasticSearch
